spring.application.name=neuro_activity
spring.data.mongodb.uri=mongodb+srv://brandonsoldado60_db_user:P3sDImIDTiJKpJmP@cluster0.djsalho.mongodb.net/neuro_activity
spring.data.mongodb.auto-index-creation=true

openai.api.key=${OPENAI_API_KEY}

app.cors.allowed-origins=*
app.cors.allow-credentials=false
server.port=8080